services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "8000:8000"
    restart: always
    shm_size: '2gb'
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    
  worker:
    build: .
    command: celery -A LCwebsite worker -l info
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - web