# Generated by Django 6.0.5 on 2026-06-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_and_address', models.CharField()),
                ('item_name', models.CharField()),
                ('item_price', models.FloatField()),
                ('item_cal', models.FloatField()),
            ],
        ),
    ]
