# Generated by Django 6.0.5 on 2026-06-02 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedstore',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 2, 21, 8, 41, 84350, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
