# Generated by Django 6.0.5 on 2026-06-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_scrapedstore_scraped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedstore',
            name='store_id',
            field=models.CharField(default='none'),
            preserve_default=False,
        ),
    ]
