# Generated by Django 6.0.5 on 2026-06-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_scrapedstore_store_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scrapedstore',
            constraint=models.UniqueConstraint(fields=('zip_and_address', 'item_name'), name='unique_store_item'),
        ),
    ]
